import { type WebsiteSettings } from '../types/settings'

export const DEFAULT_WEBSITE_SETTINGS: WebsiteSettings = {
  general: {
    websiteName: 'Surf Mangalore',
    tagline: 'Premium surf coaching and ocean-first experiences',
    logoUrl: '',
    faviconUrl: '',
    primaryEmail: 'hello@surfmangalore.com',
    primaryPhone: '+91 98765 43210',
    businessWhatsapp: '+91 98765 43210',
    timezone: 'Asia/Kolkata',
    defaultLanguage: 'en',
  },
  homepage: {
    heroTitle: 'Ride the pulse of the coast.',
    heroSubtitle: 'Step into a world of polished surf mornings, expert coaching, and unforgettable ocean energy designed for guests who want more than a lesson.',
    heroCtaButton1Label: 'Book Your Surf Session',
    heroCtaButton1Path: '/booking',
    heroCtaButton2Label: 'Explore The Experience',
    heroCtaButton2Path: '/gallery',
    heroBackgroundImageUrl: '/images/placeholders/sunset.svg',
    heroDroneShotImageUrl: '/images/placeholders/drone.svg',
    announcementBanner: 'Award-winning surf school · Mangalore',
    homepageFeaturedSectionToggle: true,
  },
  contact: {
    businessAddress: 'Malpe, Karnataka',
    googleMapsUrl: '',
    supportEmail: 'hello@surfmangalore.com',
    supportPhone: '+91 98765 43210',
    businessHours: [
      'Monday: 6:30 AM - 6:30 PM',
      'Tuesday: 6:30 AM - 6:30 PM',
      'Wednesday: 6:30 AM - 6:30 PM',
      'Thursday: 6:30 AM - 6:30 PM',
      'Friday: 6:30 AM - 7:00 PM',
      'Saturday: 6:00 AM - 7:00 PM',
      'Sunday: 6:00 AM - 7:00 PM',
    ],
    emergencyContact: '+91 98765 43210',
  },
  socialMedia: {
    instagram: '',
    facebook: '',
    youtube: '',
    linkedIn: '',
    whatsapp: '',
  },
  navigation: {
    menuItems: [
      { id: 'home', label: 'Home', path: '/', enabled: true, order: 1 },
      { id: 'about', label: 'About', path: '/about', enabled: true, order: 2 },
      { id: 'experiences', label: 'Experiences', path: '/experiences', enabled: true, order: 3 },
      { id: 'lessons', label: 'Lessons', path: '/lessons', enabled: true, order: 4 },
      { id: 'events', label: 'Events', path: '/events', enabled: true, order: 5 },
      { id: 'gallery', label: 'Gallery', path: '/gallery', enabled: true, order: 6 },
      { id: 'contact', label: 'Contact', path: '/contact', enabled: true, order: 7 },
    ],
  },
  footer: {
    footerDescription: 'Premium surf instruction, thoughtful adventure planning, and ocean-first experiences shaped around freedom and flow.',
    copyrightText: '© 2026 Surf Mangalore.',
    quickLinks: [
      { label: 'About', path: '/about' },
      { label: 'Experiences', path: '/experiences' },
      { label: 'Booking', path: '/booking' },
      { label: 'Lessons', path: '/lessons' },
      { label: 'Events', path: '/events' },
      { label: 'Gallery', path: '/gallery' },
    ],
    legalLinks: [
      { label: 'Privacy', path: '/contact' },
      { label: 'Terms', path: '/contact' },
    ],
  },
  seo: {
    defaultMetaTitle: 'Surf Mangalore',
    defaultMetaDescription: 'Premium surf school and coastal surf experiences in Mangalore.',
    openGraphImage: '/images/placeholders/ocean.svg',
    twitterImage: '/images/placeholders/ocean.svg',
    robotsTxtPlaceholder: 'index, follow, max-image-preview:large',
    googleVerificationCodePlaceholder: '',
  },
  businessInformation: {
    businessName: 'Surf Mangalore',
    registrationNumber: '',
    gstNumber: '',
    foundedYear: 2018,
  },
}
