import Badge from '../components/Badge'
import Card from '../components/Card'
import { useWebsiteSettings } from '../contexts/WebsiteSettingsContext'

type LegalSection = { title: string; paragraphs: string[] }

const privacySections: LegalSection[] = [
  { title: 'Information We Collect', paragraphs: ['We may collect your name, email address, phone number, booking details, selected lesson, experience or event, preferred dates and times, participant count, and messages submitted through contact forms. Normal website infrastructure may also generate technical information such as browser, device, IP address, and log data.'] },
  { title: 'How We Use Your Information', paragraphs: ['We use this information to process bookings, contact customers about reservations, provide support, manage lessons, experiences and events, prevent abuse and security issues, improve website operation, and maintain business records.'] },
  { title: 'Payment Information', paragraphs: ['Our current booking model is primarily payment-on-ground. Where payment is completed at the venue, Surf Mangalore does not collect online card or payment credentials through this website.'] },
  { title: 'Cookies and Authentication', paragraphs: ['Essential cookies and session mechanisms may support authenticated administration, security, and normal website operation. We do not imply the use of unnecessary advertising cookies.'] },
  { title: 'Media and Uploaded Content', paragraphs: ['Website images and media may be stored or served through third-party cloud media infrastructure necessary to deliver the site.'] },
  { title: 'Third-Party Services', paragraphs: ['The website may rely on hosting, database, media delivery, and related infrastructure providers needed to operate the service. These providers process information only as necessary for their services and applicable arrangements.'] },
  { title: 'Data Retention', paragraphs: ['Information may be retained for booking administration, customer support, legal, accounting, and business record requirements, and deleted or anonymized when no longer reasonably required.'] },
  { title: 'Data Security', paragraphs: ['We use reasonable technical and organizational safeguards, but no internet system can guarantee absolute security.'] },
  { title: "Children's Privacy", paragraphs: ['Our services may be used by minors under supervision or booking by a parent or guardian where appropriate for the activity.'] },
  { title: 'Your Choices and Requests', paragraphs: ['You may contact us to request correction or reasonable deletion or access regarding information associated with you, subject to legitimate recordkeeping obligations.'] },
  { title: 'Changes to This Policy', paragraphs: ['We may update this policy from time to time. The latest version and its update date will be shown on this page.'] },
]

const termsSections: LegalSection[] = [
  { title: 'About Surf Mangalore', paragraphs: ['This website provides information and booking or reservation functionality for surf lessons, experiences, activities, and events.'] },
  { title: 'Booking Types', paragraphs: ['Lessons are training or course-package bookings: you select an intended start date and participant count, and the confirmation represents an appointment or reservation, not an event ticket.', 'Experiences are activity or tour-style bookings: you choose from dates and time slots made available by Surf Mangalore, with participant-based pricing where indicated. A successful booking produces a booking or ticket confirmation and payment is generally made on-ground.', 'Events have a fixed date and scheduled start and end time. Customers cannot choose an arbitrary alternative date or time. A successful reservation produces an event booking or ticket confirmation and payment is generally made on-ground.'] },
  { title: 'Booking Confirmation', paragraphs: ['Bookings are subject to availability. A successful submission provides a booking reference or confirmation; retain the reference or PDF where generated. We may contact you if operational clarification is needed.'] },
  { title: 'Pricing and Payment', paragraphs: ['Displayed prices are in INR unless otherwise stated and may be per participant where indicated. Payment is generally completed on-ground or at the venue under the current booking model. Any future online-payment method will be governed by terms shown during checkout.'] },
  { title: 'Changes, Cancellations and Rescheduling', paragraphs: ['Contact Surf Mangalore as early as possible about changes. Rescheduling or cancellation depends on availability and operational conditions. Surf or ocean activities may change because of weather, sea conditions, safety, instructor availability, or other operational reasons.'] },
  { title: 'Weather, Ocean and Safety Conditions', paragraphs: ['Ocean activities depend on weather, tides, sea state, and safety assessment. Instructors or organizers may delay, modify, relocate, reschedule, or cancel a session for safety. Participants must follow staff and instructor directions.'] },
  { title: 'Participant Responsibilities', paragraphs: ['Provide accurate contact and booking information, disclose relevant information requested for safe participation, follow safety instructions, use equipment responsibly, behave respectfully toward staff, participants, the local community and environment, and arrive at the communicated time and location.'] },
  { title: 'Minors', paragraphs: ['Minors may require parent or guardian consent and supervision depending on the activity.'] },
  { title: 'Equipment', paragraphs: ['Provided boards, safety gear, and other equipment must be used according to staff instructions and returned in reasonable condition.'] },
  { title: 'Events and Experiences', paragraphs: ['Schedules, locations, instructors, and activity details may reasonably change because of operational or safety factors.'] },
  { title: 'Website Use', paragraphs: ['Do not misuse the site, seek unauthorized access, interfere with service, submit fraudulent bookings, automate abusive traffic, or copy protected website content without authorization.'] },
  { title: 'Intellectual Property', paragraphs: ['Website branding, original text, design, media, and materials belong to Surf Mangalore or their respective licensors unless otherwise stated. Third-party licensed images remain subject to their owners’ rights.'] },
  { title: 'Third-Party Links', paragraphs: ['External links and services may have their own terms and privacy practices.'] },
  { title: 'Nature of Activities', paragraphs: ['Surfing and ocean activities involve physical activity and changing environmental conditions. Participants are expected to follow safety guidance and staff instructions.'] },
  { title: 'Changes to These Terms', paragraphs: ['These terms may be updated, and the latest version will appear on this page.'] },
]

export default function LegalPage({ kind }: { kind: 'privacy' | 'terms' }) {
  const { settings } = useWebsiteSettings()
  const privacy = kind === 'privacy'
  const sections = privacy ? privacySections : termsSections
  return <div className="space-y-8"><section className="rounded-[2.4rem] border border-white/10 bg-[linear-gradient(135deg,rgba(5,21,31,0.98),rgba(8,32,46,0.92))] px-6 py-10 shadow-[var(--shadow-large)] sm:px-10 lg:px-14 lg:py-14"><Badge tone="accent">Legal</Badge><h1 className="mt-5 max-w-[14ch] font-[var(--font-heading)] text-[clamp(2.7rem,6vw,5rem)] font-[var(--font-display)] leading-[0.92] tracking-[var(--letter-tight)] text-[var(--color-text)]">{privacy ? 'Privacy Policy' : 'Terms & Conditions'}</h1><p className="mt-6 max-w-3xl text-base leading-8 text-[var(--color-text-secondary)]">{privacy ? 'Surf Mangalore respects visitor and customer privacy. This policy explains what information we collect, why it is used, and how it is handled.' : 'These terms govern use of the Surf Mangalore website and bookings for lessons, experiences, and events.'}</p><p className="mt-5 text-sm text-[var(--color-text-secondary)]">Last Updated: September 2026</p></section><div className="mx-auto max-w-4xl space-y-4">{sections.map((section) => <Card key={section.title} variant="glass" className="border-white/12 p-6 sm:p-8"><h2 className="text-xl font-semibold text-white">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-4 text-sm leading-8 text-[var(--color-text-secondary)]">{paragraph}</p>)}</Card>)}<Card variant="glass" className="border-white/12 p-6 sm:p-8"><h2 className="text-xl font-semibold text-white">Contact Us</h2><p className="mt-4 text-sm leading-8 text-[var(--color-text-secondary)]">For questions about this {privacy ? 'policy' : 'terms document'}, contact Surf Mangalore.</p><div className="mt-4 space-y-1 text-sm text-[var(--color-text-secondary)]"><p>{settings.general.primaryEmail}</p><p>{settings.general.primaryPhone}</p><p>{settings.contact.businessAddress}</p></div></Card></div></div>
}
